# Generated by Django 2.0.7 on 2018-08-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180829_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='signer_postcode',
            field=models.CharField(default='', max_length=11, verbose_name='邮编'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='message_type',
            field=models.IntegerField(choices=[(1, '留言'), (3, '咨询'), (2, '投诉'), (4, '售后')], default=1, help_text='留言类型: 1(留言),2(投诉),3(咨询),4(售后)', verbose_name='留言类型'),
        ),
    ]
