# Generated by Django 2.0.7 on 2018-08-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodscategory',
            name='desc',
        ),
    ]
