# Generated by Django 2.0.7 on 2018-08-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_goodscategory_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodscategory',
            name='add_time',
        ),
    ]
