# Generated by Django 2.0.7 on 2018-08-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_goodscategory_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_desc',
            field=models.TextField(null=True),
        ),
    ]
