# Generated by Django 2.0.7 on 2018-08-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_goods_goods_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscategory',
            name='category_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='封面图'),
        ),
    ]
