# Generated by Django 2.0.7 on 2018-08-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='is_select',
            field=models.BooleanField(default=True),
        ),
    ]
