# Generated by Django 2.0.7 on 2018-08-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20180827_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_CLOSE', '交易关闭'), ('paying', '待支付'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_SUCCESS', '成功'), ('TRADE_FINISHED', '交易结束')], default='paying', max_length=20, verbose_name='交易状态'),
        ),
    ]
