# Generated by Django 2.0.7 on 2018-08-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20180829_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_SUCCESS', '成功'), ('paying', '待支付'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_CLOSE', '交易关闭'), ('TRADE_FINISHED', '交易结束')], default='paying', max_length=20, verbose_name='交易状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='支付时间'),
        ),
    ]
